version: '3.8'
services:
  web:
    build: .
    volumes:
      - asdf-data:/data
      - asdf-data:/certs
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: webfinger
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: webfinger
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  asdf-data: